### ISSUE TITLE
dont work

### ISSUE THREAD

**Issue by behroozbc** [yohaneslumentut/ng-ripple-module#1]
hi 
i install your package and i got an error 
please make document better 
![image](https://user-images.githubusercontent.com/20381616/48312154-c582d480-e5bf-11e8-8ffc-0b72ed44464b.png)

**Comment by yohaneslumentut** [comment]
hi.
thanks for trying. would you like to screen shoot the result of ng --version of your environment? The error message clearly show us that No provider for animation builder. Can you share your app.module ts code?

**Comment by behroozbc** [comment]
yes 
![image](https://user-images.githubusercontent.com/20381616/48313118-21078f00-e5cd-11e8-8ad8-ebd2fc0cac4e.png)
![image](https://user-images.githubusercontent.com/20381616/48313141-501e0080-e5cd-11e8-9da3-b97c68a97592.png)

**Comment by yohaneslumentut** [comment]
I don't see you import ng-ripple-module in your app.module.ts. Please share your package.json at the root of your project. Do you clone the code or install using npm?

Please read the README.md at the installation section.
In your app.module.ts import `BrowserAnimationsModule`  after `BrowserModule` and `NgRippleModule` after `NgbModule`.
```ts
import { BrowserModule } from '@angular/platform-browser';
import { BrowserAnimationsModule } from '@angular/platform-browser/animations';
...
// package
import { NgbModule } from  '@ng-bootstrap/ng-bootstrap';
import { NgRippleModule } from 'ng-ripple-module';
...
@NgModule({
  declarations: [
    AppComponent
   ...
  ],
  imports: [
    ...
    BrowserModule,
    BrowserAnimationsModule,
    ...
    NgbModule,
    NgRippleModule,
    ...
  ],
  ...
})
```

**Comment by behroozbc** [comment]
thanks 
I change the code and I forget and send the code that haven't NgRippleModule 
i forget to add BrowserAnimationsModule

**Comment by yohaneslumentut** [comment]
thanks too. By this issue i found a minor error (change detection error). I've just publish new version to fix the error.
issue closed.
