### ISSUE TITLE
Doesnt work with IONIC

### ISSUE THREAD

**Issue by brunnohofmann** [yohaneslumentut/ng-ripple-module#3]
Im trying to use it witk IONIC v3, but the (click) attr, but if use the ripple directive, never work. Even with button, a or any tag.

The ripple effect works, but the (click) funcionalitty doesnt.

`
 <a href="#" ripple ion-button (click)="checkAnswer(alternative)">
            {{alternative.alt}}
          </a>
`

**Comment by yohaneslumentut** [comment]
would you like to read/implement as writen in this wiki first? https://github.com/yohaneslumentut/ng-ripple-module/wiki/5.Ripple-Events

**Comment by brunnohofmann** [comment]
Ohhh man...
So sorry... 
Its work now...
Thank u so much

**Comment by yohaneslumentut** [comment]
I'm glad to know that its work. U r welcome.
